<?php 

function sum_menu() {
    $items = array();
    $items['sum'] = array(
        'title' => 'Calculate Sum',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('sum_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['success'] = array(
        'title' => 'Success',
        'page callback' => 'sum_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function sum_form() {
    $form = array();

    $form['left_operand'] = array(
        '#title' => 'Left Operand',
        '#type' => 'textfield',
        '#description' => t('Please enter your starting number.'),
    );

    $form['right_operand'] = array(
        '#title' => 'Right Operand',
        '#type' => 'textfield',
        '#description' => t('Please enter a number to add to the starting number.'),
    );    

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Calculate Sum',
    );

    return $form;
}

function sum_form_submit($form, &$form_state) {
    $first_number = $form_state['values']['left_operand'];
    $second_number = $form_state['values']['right_operand'];
    $sum = $first_number + $second_number;
    $_SESSION['sum_output'] = $sum;


    $form_state['redirect'] = 'success';
}

function sum_success() {
    $answer = $_SESSION['sum_output'];
    return 'You calculated a sum! The answer is: $answer';
}