<?php 
/**
* @file
* Play with form api.
*/

/**
* Implements hook_menu
* ping_pong page callback is calling an existing Drupal function to create a form.
*/

function ping_pong_menu() {
    $items['ping_pong'] = array(
        'title' => 'Ping Pong Problem',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('ping_pong_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['success'] = array(
        'title' => 'Success',
        'page callback' => 'ping_pong_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}


/**
* Define a form.
*/
function ping_pong_form() {
    //create field for username. field name is key, value is array of info for that field.
    $form['count_max'] = array(
        '#title' => 'Count Maximum',
        '#type' => 'textfield',
        '#description' => t('Please enter the number to count up to.'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );

    return $form;
}

/**
* Validate using the standard formid_validate function. formid = ping_pong_form.
*/
function ping_pong_form_validate($form, &$form_state) {
    // if ($form_state['values']['user_name'] == 'King Kong') {
    //     form_set_error('user_name', 'You can not be King Kong.');
    // }
    //form_set_error function tells drupal that something failed and the form is displayed again with errors.
}

/**
* Handle post validation form submission.
* standard function formid_submit
*/
function ping_pong_form_submit($form, &$form_state) {

    $count_max = $form_state['values']['count_max'];
    $pingpong_output = array();
    
    for ($i=1; $i <= $count_max; $i++) { 
        if ($i % 3 == 0 && $i % 5 == 0) {
            array_push($pingpong_output, "ping-pong");   
        } elseif ($i % 3 == 0) {
            array_push($pingpong_output, "ping");   
        } elseif ($i % 5 == 0) {
            array_push($pingpong_output, "pong");   
        } else {
            array_push($pingpong_output, $i);   
        }
    }

    $_SESSION['ping_pong_output'] = $pingpong_output;
    $form_state['redirect'] = 'success';
}

function ping_pong_success() {
    $output = '<ul>';
    foreach ($_SESSION['ping_pong_output'] as $value) {
        $output = $output . '<li>' . $value . '</li>';         
    }
    $output = $output . '</ul>';
    return "Hooray! $output";
}